Develop
Artanic30/SISTOJ pull request #25
Opened 2019-02-18 15:52 UTC by Artanic30

2019-02-19 02:50 UTC, harveyqiu approved these changes
并不知道在干嘛
就不能pr里写下自己干嘛了吗

2019-02-19 13:06 UTC, Artanic30 commented
> 并不知道在干嘛
> 就不能pr里写下自己干嘛了吗

2019-02-19 13:13 UTC, Artanic30 commented
<img width="1437" alt="2019-02-19 9 11 59" src="https://user-images.githubusercontent.com/25761235/53017509-1e99b880-348b-11e9-95c6-d84e4b1f483e.png">
![Uploading 屏幕快照 2019-02-19 下午9.11.35.png…]()

2019-02-19 13:36 UTC, Artanic30 commented
<img width="721" alt="2019-02-19 9 11 35" src="https://user-images.githubusercontent.com/25761235/53017555-37a26980-348b-11e9-9be6-2a2c191d5fbf.png">
<img width="1437" alt="2019-02-19 9 11 59" src="https://user-images.githubusercontent.com/25761235/53017558-38d39680-348b-11e9-92a4-00c315ce7ba9.png">

2019-02-19 17:21 UTC, nichujie commented
为啥点了login按钮就isAuthorized了，isRequest又是啥，这业务逻辑不是很懂

2019-02-20 04:43 UTC, nichujie commented on src/instructor/components/AddCourse/Add.vue
> +  .row-main {
提交之前要么command + option + L，要么人眼检查样式，这没对齐

2019-02-20 04:43 UTC, nichujie commented on src/instructor/components/AddCourse/Add.vue
> +  .row-main {
检查格式，打错了

2019-02-20 04:50 UTC, nichujie commented on src/instructor/components/AddCourse/State.vue
> +            >
这参差不齐的tag闹哪样

2019-02-20 04:53 UTC, nichujie approved these changes

2019-02-20 15:36 UTC, Artanic30 commented
想实现的在点击了table的一行后向后段申请当前作业的judges信息
然后再下拉列表显示出来，但是数据请求来后judges没有同步跟新

2019-02-21 02:28 UTC, nichujie commented on src/instructor/components/CourseJudges/Add.vue
> +      this.axios.get(`/judge/`)
所以这为什么有个this

2019-02-21 02:31 UTC, nichujie commented on src/instructor/components/CourseJudges/Main.vue
> +                <div>{{ judgeInfo.max_job}}</div>
reformat

2019-02-21 02:41 UTC, alienmao commented on src/instructor/components/CourseJudges/Add.vue
> +      this.axios.get(`/judge/`)
对的，他写的没错
axios绑在vue对象上了

2019-02-21 02:42 UTC, nichujie commented on src/instructor/components/CourseJudges/Add.vue
> +      this.axios.get(`/judge/`)
是真🐂

2019-02-21 02:47 UTC, harveyqiu requested changes
一次提交太多代码了

2019-02-21 02:47 UTC, alienmao commented on src/instructor/components/AddAssignment/State.vue
> +        max_job: 'Please choose on of your judges'
这什么英语

2019-02-21 02:47 UTC, alienmao commented on src/instructor/components/AddAssignment/State.vue
> +        max_job: 'Please choose on of your judges'
choose on of???

2019-02-21 02:47 UTC, alienmao commented on src/instructor/components/AddCourse/Index.vue
> +        </el-menu>
reformat

2019-02-21 02:47 UTC, alienmao commented on src/instructor/components/AddCourse/Index.vue
> +    float: left!important;
cao 
!important前面要加空格！

2019-02-21 02:47 UTC, alienmao commented on src/instructor/components/AddCourse/State.vue
> +.row-quarter {
不注释缩进
没有代码洁癖
垃圾

2019-02-23 12:35 UTC, merged